# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 440)
        MainWindow.setMinimumSize(QtCore.QSize(500, 440))
        MainWindow.setMaximumSize(QtCore.QSize(500, 440))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(540, 540))
        self.centralwidget.setObjectName("centralwidget")
        self.btnSingUpReg = QtWidgets.QPushButton(self.centralwidget)
        self.btnSingUpReg.setGeometry(QtCore.QRect(150, 310, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSingUpReg.setFont(font)
        self.btnSingUpReg.setObjectName("btnSingUp")
        self.leName = QtWidgets.QLineEdit(self.centralwidget)
        self.leName.setGeometry(QtCore.QRect(110, 110, 130, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.leName.setFont(font)
        self.leName.setToolTip("")
        self.leName.setWhatsThis("")
        self.leName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.leName.setText("")
        self.leName.setObjectName("leFirstName")
        self.leSurname = QtWidgets.QLineEdit(self.centralwidget)
        self.leSurname.setGeometry(QtCore.QRect(260, 110, 130, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.leSurname.setFont(font)
        self.leSurname.setToolTip("")
        self.leSurname.setWhatsThis("")
        self.leSurname.setInputMethodHints(QtCore.Qt.ImhNone)
        self.leSurname.setText("")
        self.leSurname.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leSurname.setObjectName("leLastName")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 170, 90, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 135, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 90, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 210, 65, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 90, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lePassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lePassword.setGeometry(QtCore.QRect(110, 150, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lePassword.setFont(font)
        self.lePassword.setToolTip("")
        self.lePassword.setWhatsThis("")
        self.lePassword.setInputMethodHints(
            QtCore.Qt.ImhHiddenText | QtCore.Qt.ImhNoAutoUppercase | QtCore.Qt.ImhNoPredictiveText | QtCore.Qt.ImhSensitiveData)
        self.lePassword.setText("")
        self.lePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lePassword.setObjectName("lePassword")
        self.leConPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.leConPassword.setGeometry(QtCore.QRect(110, 190, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.leConPassword.setFont(font)
        self.leConPassword.setToolTip("")
        self.leConPassword.setWhatsThis("")
        self.leConPassword.setInputMethodHints(
            QtCore.Qt.ImhHiddenText | QtCore.Qt.ImhNoAutoUppercase | QtCore.Qt.ImhNoPredictiveText | QtCore.Qt.ImhSensitiveData)
        self.leConPassword.setText("")
        self.leConPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leConPassword.setObjectName("leConPassword")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 60, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.leAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.leAddress.setGeometry(QtCore.QRect(110, 230, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.leAddress.setFont(font)
        self.leAddress.setToolTip("")
        self.leAddress.setWhatsThis("")
        self.leAddress.setInputMethodHints(
            QtCore.Qt.ImhHiddenText | QtCore.Qt.ImhNoAutoUppercase | QtCore.Qt.ImhNoPredictiveText | QtCore.Qt.ImhSensitiveData)
        self.leAddress.setText("")
        self.leAddress.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leAddress.setObjectName("leAddress")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 250, 95, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.leApartNum = QtWidgets.QLineEdit(self.centralwidget)
        self.leApartNum.setGeometry(QtCore.QRect(110, 270, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.leApartNum.setFont(font)
        self.leApartNum.setToolTip("")
        self.leApartNum.setWhatsThis("")
        self.leApartNum.setInputMethodHints(
            QtCore.Qt.ImhHiddenText | QtCore.Qt.ImhNoAutoUppercase | QtCore.Qt.ImhNoPredictiveText | QtCore.Qt.ImhSensitiveData)
        self.leApartNum.setText("")
        self.leApartNum.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.leApartNum.setObjectName("leApartNum")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registration"))
        self.btnSingUpReg.setText(_translate("MainWindow", "SIGN UP"))
        self.label.setText(_translate("MainWindow", "Confirm password"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Street"))
        self.label_5.setText(_translate("MainWindow", "Surname"))
        self.label_6.setText(_translate("MainWindow", "Registration"))
        self.label_7.setText(_translate("MainWindow", "Apartment number"))


